### ISSUE TITLE
 Session token may have expired

### ISSUE THREAD

**Issue by bystart** [LiLittleCat/ChatGPT#1]
Session token may have expired 拿到正在使用的session token 提示过期

**Comment by LiLittleCat** [comment]
好像是 ChatGPT 加强了验证，我再研究研究

**Comment by LiLittleCat** [comment]
ChatGPT 加了 Cloudflare 之后，只用 session token 请求直接就 403 了。

**Comment by MoLu10086** [comment]
所以现在有解决方法了吗？

**Comment by LiLittleCat** [comment]
@MoLu10086 没有，等官方 API 吧。☹

**Comment by LiLittleCat** [comment]
@bystart @MoLu10086 使用官方 API 了，升级 1.0.0 使用。
