### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by Jinthium** [LiLittleCat/ChatGPT#10]
14:49:46.480 [Client thread] ERROR com.lilittlecat.chatgpt.offical.ChatGPT - Request failed: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
, please try again

**Comment by LiLittleCat** [comment]
此错误消息表示您已达到 API 的每月最大支出（硬性限制）。这意味着您已经消耗了分配给您的计划的所有积分或单位，并且已经达到了您的计费周期的限制。参阅：https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
